// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseOverview } from "./ReleaseOverview";

export interface Artist { id: string, name: string, releases: Array<ReleaseOverview>, backgroundSrc: string | null, }