// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryReleaseTrack } from "./LibraryReleaseTrack";

export interface LibraryRelease { id: string, artistCreditId: string, artistCreditName: string, name: string, date: string, totalTracks: number, totalDiscs: number, tracks: Array<LibraryReleaseTrack>, coverArtSrc: string | null, }