// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryReleasesItem } from "./LibraryReleasesItem";

export interface LibraryArtist { id: string, name: string, releases: Array<LibraryReleasesItem>, }