// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbArtist } from "./DbArtist";

export interface PlayerTrack { id: string, releaseId: string, releaseName: string, name: string, artistCreditName: string, artists: Array<DbArtist>, thumbnailSrc: string | null, }