// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackState } from "./PlaybackState";

export interface PlayerState { playbackState: PlaybackState, position: number, totalTime: number, path: string | null, }