// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseTrack } from "./ReleaseTrack";

export interface Release { id: string, artistCreditId: string, artistCreditName: string, name: string, date: string, totalTracks: number, totalDiscs: number, tracks: Array<ReleaseTrack>, coverArtSrc: string | null, }