// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Release { id: string, artistCreditId: string, name: string, date: string, totalTracks: number, totalDiscs: number, }