// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ReleaseOverview { id: string, name: string, artistCreditName: string, thumbnailSrc: string | null, }