// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanStateKind } from "./ScanStateKind";

export interface ScanState { kind: ScanStateKind, progress: [number, number] | null, }