// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanStatePhase } from "./ScanStatePhase";

export interface ScanState { progress: [number, number] | null, phase: ScanStatePhase, }