// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtistOverview } from "./ArtistOverview";
import type { ReleaseOverview } from "./ReleaseOverview";

export interface SearchResult { releases: Array<ReleaseOverview>, artists: Array<ArtistOverview>, }