// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryArtistsItem } from "./LibraryArtistsItem";
import type { LibraryReleasesItem } from "./LibraryReleasesItem";

export interface SearchResult { releases: Array<LibraryReleasesItem>, artists: Array<LibraryArtistsItem>, }