// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Track { id: string, releaseId: string, artistCreditId: string, name: string, length: number, trackNumber: number, discNumber: number, path: string, }