[package]
name = "grass-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bass-sys = { path = "bass-sys" }
bassmix-sys = { path = "bassmix-sys" }
thiserror = "1.0"
crossbeam = "0.8"